# Generated by Django 3.2.12 on 2022-02-10 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=230)),
                ('age', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.TextField()),
                ('where_to', models.TextField()),
                ('how_many', models.TextField()),
                ('arrivals', models.DateTimeField()),
                ('leaving', models.DateField()),
            ],
        ),
    ]
