# Generated by Django 3.2.12 on 2022-02-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idukkiapp', '0002_auto_20220210_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='arrivals',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='leaving',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
